config/routes.rb
Rails.application.routes.draw do
 

  get 'people/index'

  get 'people/new'

  get 'people/show'

  get 'people/edit'

  get 'people/delete'

  get 'subjects/index'

  get 'subjects/show'

  get 'subjects/new'

  get 'subjects/edit'

  get 'subjects/delete'

  get 'aboutus', to: 'page#about_us'

  get 'products', to: 'page#product'

  get 'newsletter', to: 'page#newsletter'

  get 'blog', to: 'page#blog'

  get 'calender', to: 'page#calender'

  get 'articles', to: 'page#articles'

  get 'login', to:'page#login'

  root 'static_page#home'
  get 'home', to: 'static_page#home'

  get 'help', to: 'static_page#help'

  get 'contact', to: 'static_page#contact'
   post 'contact', to: 'static_page#contact'

match ':controller(/:action (/:id))', :via=>[:get, :post]

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/people.rb
class People < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
has_many :pages

scope :visible, lambda {where(:visible =>true)}
scope :invisible, lambda {where(:visible =>false)}
scope :sorted, lambda {order("subjects.position ASC")}
scope :newest_first, lambda {order("subjects.created_at DESC")}
scope :search, lambda {|query|
where(["name LIKE ?", "%#{query}%"])

}


end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def about_us
  end

  def product
  end

  def newsletter
  end

  def blog
  end

  def calender
    @time = Time.now

  end

  def articles
  end

  def login
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = People.all
    if !@people
      flash[:notice] ='No body has registered'
      redirect_to(:action =>'index')

end
  end

  def new
    @people = People.new
  end

  def create

    @people = People.new(people_params)

  if @people.save
     flash[:notice] ="You have successfully created '#{@people.first_name}  #{@people.last_name}'  as new Person"
    redirect_to(:action =>'index')
  else
   
render(:action =>'new')
end

  end

  def show
    @people = People.find(params[:id])
  end

  def edit
 @people = People.find(params[:id])

  end

  def update
    @people = People.find(params[:id])

    if @people.update_attributes(people_params)

      flash[:notice] = " '#{@people.first_name}' has successfully been edited "
      redirect_to(:action =>'index')

    else
      render(:action =>'edit')
    end
  end

  def delete
     @people = People.find(params[:id])
  end

 def destroy
@people = People.find(params[:id]) 
@people.destroy
flash[:notice] ="You have successfully deleted '#{@people.first_name}' from your list of subjects "
redirect_to(:action =>'index')

  end

private
def people_params
params.require(:people).permit(:first_name, :last_name, :sex, :visible, :age, :state, :address,:hobbies, :profession)

end


end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home

   @Jesus ='God'

  @vine='the Resurrection and the Life'

  @date = Date.today
  end

  def help
  end

  def contact
  	@name = params["name"]
	
	if @name ==""

  	@error_msg = "You have an empty field"

  end

  	@email = params["email"]
    @textarea=params["textarea"]

     @newsletter = params["newsletter"] =="newsletter"

     gender=params["gender"]

     @male = gender=="Male"
     @female = gender=="Female"

  	
	 end


end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout false
  def index
@subjects = Subject.sorted

  end

  def show

   @subject = Subject.find(params[:id]) 
  end

  def new
@subject = Subject.new

  end

  def create
@subject = Subject.new(subject_params)

  if @subject.save
     flash[:notice] ="You have successfully created '#{@subject.name}'  as new subject"
    redirect_to(:action =>'index')
  else
   
render(:action =>'new')
end

  end

  def edit
    
 @subject = Subject.find(params[:id]) 

  end
  def update
@subject = Subject.find(params[:id])

  if @subject.update_attributes(subject_params)
    flash[:notice] ="Your subject '#{@subject.name}' has been successfully  edited"
  redirect_to(:action =>'show', :id=>@subject.id)
  else

render(:action =>'edit')
end

  end

  def delete
@subject = Subject.find(params[:id]) 

end

def destroy
@subject = Subject.find(params[:id]) 
@subject.destroy
flash[:notice] ="You have successfully deleted '#{@subject.name}' from your list of subjects "
redirect_to(:action =>'index')




  end

  private 
  def subject_params
    params.require(:subject).permit(:name, :visible, :position)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
 def calender




cal = "<table border = '1'>\n\t<tr>\n"
days = %w(Sun Mon Tue Wed Thur Fri Sat)

days.each do | day |

cal += "\t\t<td>#{day}</td>\n"
 end

cal += "\t</tr>\n</table>\n"

   return cal



end


end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Custo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper"><!-- #wrapper -->

	<header><!-- header -->
		<h1><a href="#">Face of Ruby</a></h1>
		<h2>Mabel Cusmetics</h2>
		<%= image_tag('cowboyup.jpg', size: "940x200") %><!-- header image -->
	</header><!-- end of header -->
	
	<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<li><%= link_to("Home",home_path) %></li>
				<li><a href="#">About</a>
			    <ul>
   					<li><%= link_to("History", aboutus_path) %></li>
   					
   				</ul>
  			</li>
				<li><%= link_to("products",products_path) %>
				</li>
				<li><%= link_to("articles",articles_path )%>
				
				</li>
				<li><%= link_to "Contact Us",contact_path %></li>

				<li><%= link_to "Blog",blog_path %></li>
				<li><%= link_to "Log in",login_path %></li>
			</ul>
		</div>
	</nav><!-- end of top nav -->


	<section id="main"><!-- #main content and sidebar area -->
		<section id="container"><!-- #container -->
			<section id="content"><!-- #content -->





<%= yield %>

	</section><!-- end of #content -->
		</section><!-- end of #container -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Things To Do</h3>
					<ul>
						<li><a href="#">Play Games</a></li>
						<li><a href="#">Chat With Friends</a></li>
						<li><a href="#">Swap Stories</a></li>
						<li><a href="#">Sell Stuff</a></li>
						<li><a href="#">Buy Stuff</a></li>
						<li><a href="#">Trade Stuff</a></li>
					</ul>
					
				<h3>Our Sponsors</h3>
					<%= image_tag('ad125.jpg') %> <%= image_tag('ad125.jpg') %><br/>
					<%= image_tag('ad125.jpg') %> <%= image_tag('ad125.jpg') %><br/>
					

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
					</ul>

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->

	<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside id="first" class="footer-segment">
							<h3>Blogroll</h3>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
									<li><a href="#">four linkylinks</a></li>
									<li><a href="#">five linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside id="second" class="footer-segment">
							<h3>Awesome Stuff</h3>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
									<li><a href="#">four linkylinks</a></li>
									<li><a href="#">five linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside id="third" class="footer-segment">
							<h3>Coolness</h3>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
									<li><a href="#">four linkylinks</a></li>
									<li><a href="#">five linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->
					
					<aside id="fourth" class="footer-segment">
							<h3>Blahdyblah</h3>
								<p>Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.</p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of #footer-outer-block -->

		</section><!-- end of #footer-area -->
	</footer>

</div><!-- #wrapper -->

</body>
</html>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/calender.html.erb
<h1>Carlender</h1>

<%=mail_to("manga89ers@yahoo.com", "Email me")%>
<%= @time.year %> <%= @time.strftime("%B")%> <%= @time.day%>
<%=calender.html_safe %>
</br>

app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

app/views/page/newsletter.html.erb
<h1>Page#newsletter</h1>
<p>Find me in app/views/page/newsletter.html.erb</p>

app/views/page/product.html.erb
<h1>Page#product</h1>
<p>Find me in app/views/page/product.html.erb</p>

app/views/people/delete.html.erb
<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects new">
	<h2>Remove <%=@people.first_name%> Profile</h2>
<%= form_for(:people, :url=> {:action =>'destroy', :id=>@people.id}) do |f| %>

<p> Are You sure you want to delete <%=@people.first_name%>

<div class ="form-buttons">
	<%=submit_tag("Delete")%>
</div>

<% end %>




</div>

app/views/people/edit.html.erb
<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects new">
	<h2>Edit <%=@people.first_name%>'s Profile</h2>
<%= form_for(:people, :url=> {:action =>'update', :id=> @people.id}) do |f| %>

<table summary ="Subject form fields">

<tr>
	<th>First Name</th>
	<th><%=f.text_field(:first_name)%>
	</th>
	</tr>

<tr>
	<th>Last Name</th>
	<th><%=f.text_field(:last_name)%>
	</th>
	</tr>

<tr>
	<th>Sex</th>
	<th><%=f.text_field(:sex)%>
	</th>


	<tr>
	<th>State</th>
	<th><%=f.text_field(:state)%>
	</th>


	<tr>
	<th>Visible</th>
	<th><%=f.text_field(:visible)%>
	</th>

	<tr>
	<th>Age</th>
	<th><%=f.text_field(:age)%>
	</th>

	<tr>
	<th>Address</th>
	<th><%=f.text_field(:address)%>
	</th>

	<tr>
	<th>Hobby</th>
	<th><%=f.text_field(:hobbies)%>
	</th>
	<tr>
	<th>Profession</th>
	<th><%=f.text_field(:profession)%>
	</th>
	</tr>
</table>
<div class ="form-buttons">
	<%=submit_tag("Update")%>
</div>

<% end %>




</div>

app/views/people/index.html.erb
<% if !flash[:notice].blank? %>
<div class ="notice"><%= flash[:notice]%>

</div>
	<%end%>


<div class = "subjects index">
	<h2>List of Registered Persons</h2>

<%= link_to("Add New Persons", {:action => 'new'}, :class=>'action new')%>
<table class="menu1" summary="People list">
	<tr class = "header">
		<th>&nbsp;</th>
		<th class="menu2">First Name</th>
		<th class="menu2">Last Name</th>
		<th class="menu2"> Sex</th>
		<th class="menu2">State</th>
	</tr>
	<% @people.each do |people| %>
	<tr>
		<td><%= people.first_name %><td>
		<td><%= people.last_name %></td>
		<td class="center"><%= people.sex %></td>
		<td class="center"><%= people.state %></td>   
		<td class="actions">
		<%= link_to("show", {:action=> 'show', :id=>people.id}, :class =>'action show') %>
		<%= link_to("edit", {:action => 'edit', :id =>people.id}, :class =>'action edit') %>
		<%= link_to("delete", {:action => 'delete', :id => people.id}, :class =>'action delete') %>
	</td>
</tr>
<% end %>
</table>
</div>

app/views/people/new.html.erb
<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects new">
	<h2>Create New Person's List</h2>
<%= form_for(:people, :url=> {:action =>'create'}) do |f| %>

<table summary ="Subject form fields">

<tr>
	<th>First Name</th>
	<th><%=f.text_field(:first_name)%>
	</th>
	</tr>

<tr>
	<th>Last Name</th>
	<th><%=f.text_field(:last_name)%>
	</th>
	</tr>

<tr>
	<th>Sex</th>
	<th><%=f.text_field(:sex)%>
	</th>


	<tr>
	<th>State</th>
	<th><%=f.text_field(:state)%>
	</th>


	<tr>
	<th>Visible</th>
	<th><%=f.text_field(:visible)%>
	</th>

	<tr>
	<th>Age</th>
	<th><%=f.text_field(:age)%>
	</th>

	<tr>
	<th>Address</th>
	<th><%=f.text_field(:address)%>
	</th>

	<tr>
	<th>Hobby</th>
	<th><%=f.text_field(:hobbies)%>
	</th>
	<tr>
	<th>Profession</th>
	<th><%=f.text_field(:profession)%>
	</th>
	</tr>
</table>
<div class ="form-buttons">
	<%=submit_tag("Create")%>
</div>

<% end %>




</div>

app/views/people/show.html.erb
<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects show">
	<h2><%=@people.first_name%> <%=@people.last_name%> Profile </h2>

	<table summary="Subject detail view">
		<tr>
			<th>First Name</th>
			<td><%=@people.first_name%></td>
		</tr>
		<tr>
			<th>Last Name</th>
			<td><%=@people.last_name %></td>
		</tr>

		<tr>
			<th>Sex</th>
			<td><%=@people.sex %></td>
		</tr>
		<tr>
			<th>Age</th>
			<td><%=@people.age %></td>
		</tr>
		<tr>
			<th>State</th>
			<td><%=@people.state %></td>
		</tr>

		<tr>
			<th>Hobby</th>
			<td><%=@people.hobbies %></td>
		</tr>

		<tr>
			<th>Address</th>
			<td><%=@people.address %></td>
		</tr>
		<tr>
			<th>Profession</th>
			<td><%=@people.profession%></td>
		</tr>

		<tr>
			<th>Visible?</th>
			<td><%=@people.visible ? 'true' : 'false' %></td></tr>
			<tr>



				<th>Created</th>
				<td><%=@people.created_at %></td>
			</tr>
			<tr>
				<th>Updated</th>
				<th><%=@people.updated_at %></td>
				</tr>
			</table>
		</div>

app/views/static_page/contact.html.erb
<h1>Contact us</h1>

<%=@error_msg %></br>
Your name is <%= @name%> and your email address is <%= @email%>
<%= form_for contact_path method: "POST" do %>
<table>

	<tr>

<td><%=label_tag :name , "Full Name:" %></td>
<td>
<%= text_field_tag :name, @name, autofocus: "autofocus", placeholder: "Enter your name"%><br/><td></tr>

<tr><td>
<%=label_tag :email , "Email Address:" %></td><td>
<%= email_field_tag :email, @email, placeholder: "something@domain.com" %><br/></td></tr>
<tr><td>
<%=label_tag :textarea, "What happened?"%><br/></td><td>
<%=text_area_tag :textarea, @textarea, placeholder: "Type watin happen", size: "50x20" %></br></td></tr>

<tr><td>
<%=label_tag :newsletter, "Subscribe" %><br/></td><td>
<%=check_box_tag :newsletter, @newsletter %></br></td></tr>


<tr><td>
<%=label_tag :gender, "Male" %><br/></td><td>
<%=radio_button_tag :gender, @male %></br></td></tr>

<tr><td>
<%=label_tag :gender, "Female" %><br/></td><td>
<%=radio_button_tag :gender, @female %></br></td></tr>





</table>
<%=select_tag :color, options_for_select([['red',1],['green',2], ['blue',3]]) %><br/>
<%= submit_tag "Ask us something"%>

<% end %>

app/views/static_page/help.html.erb
<h1>StaticPage#help</h1>
<p>Find me in app/views/static_page/help.html.erb</p>

app/views/static_page/home.html.erb
<h1>StaticPage#home</h1>
<p>

	

	<%='in the begining ' + @Jesus%><br/>

	<p> Jesus is the <%=@vine %><p/></br>

		<%= @date %><br/>

		<%= link_to 'Contact Us', contact_path %></br>


<%= 1+1 %>
</p>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_area :position %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.text_area :visible %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/delete.html.erb
<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects delete">
	<h2>Delete Subject</h2>
<%= form_for(:subject, :url=> {:action =>'destroy', :id=>@subject.id}) do |f| %>

<p> Are you sure you want to permanently delete this subject?!!</p>

<p class ="reference-name"><%= @subject.name%></p>


<div class ="form-buttons">
	<%=submit_tag("Delete Subject")%>
</div>

<% end %>

</div>

app/views/subjects/edit.html.erb
<% if !flash[:notice].blank? %>
<div class ="notice"><%= flash[:notice]%>

</div>
	<%end%>

<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects new">
	<h2>Create New Subject</h2>
<%= form_for(:subject, :url=> {:action =>'update', :id=>@subject.id}) do |f| %>

<table summary ="Subject form fields">

<tr>
	<th>Name</th>
	<th><%=f.text_field(:name)%>
	</th>
	</tr>

<tr>
	<th>Posision</th>
	<th><%=f.text_field(:position)%>
	</th>
	</tr>

<tr>
	<th>Visible</th>
	<th><%=f.text_field(:visible)%>
	</th>
	</tr>
</table>
<div class ="form-buttons">
	<%=submit_tag("Update")%>
</div>

<% end %>




</div>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank? %>
<div class ="notice"><%= flash[:notice]%>

</div>
	<%end%>


<div class = "subjects index">
	<h2>Subjects</h2>

<%= link_to("Add New Subjects", {:action => 'new'}, :class=>'action new')%>
<table class="listing" summary="Subject list">
	<tr class = "header">
		<td>&nbsp;</td>
		<td>Subject</td>
		<td>Visible</td>
		<td>Pages</td>
		<td>Actions</td>
	</tr>
	<% @subjects.each do |subject| %>
	<tr>
		<td><%= subject.position %><td>
		<td><%= subject.name %></td>
		<td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
		<td class="center"><%= subject.pages.size %></td>   
		<td class="actions">
			<%= link_to("show", {:action=> 'show', :id=>subject.id}, :class =>'action show') %>
		<%= link_to("edit", {:action => 'edit', :id =>subject.id}, :class =>'action edit') %>
		<%= link_to("delete", {:action => 'delete', :id => subject.id}, :class =>'action delete') %>
	</td>
</tr>
<% end %>
</table>
</div>

app/views/subjects/new.html.erb
<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects new">
	<h2>Create New Subject</h2>
<%= form_for(:subject, :url=> {:action =>'create'}) do |f| %>

<table summary ="Subject form fields">

<tr>
	<th>Name</th>
	<th><%=f.text_field(:name)%>
	</th>
	</tr>

<tr>
	<th>Posision</th>
	<th><%=f.text_field(:position)%>
	</th>
	</tr>

<tr>
	<th>Visible</th>
	<th><%=f.text_field(:visible)%>
	</th>
	</tr>
</table>
<div class ="form-buttons">
	<%=submit_tag("Create Subject")%>
</div>

<% end %>




</div>

app/views/subjects/show.html.erb
<% if !flash[:notice].blank? %>
<div class ="notice"><%= flash[:notice]%>

</div>

	<%end%>
<%=link_to("<< Back to List", {:action => 'index'}, :class =>'back-link')%>
<div class ="subjects show">
	<h2>Show Subjects</h2>

	<table summary="Subject detail view">
		<tr>
			<th>Name</th>
			<td><%=@subject.name%></td>
		</tr>
		<tr>
			<th>Position</th>
			<td><%=@subject.position %></td>
		</tr>
		<tr>
			<th>Visible?</th>
			<td><%=@subject.visible ? 'true' : 'false' %></td></tr>
			<tr>
				<th>Created</th>
				<td><%=@subject.created_at %></td>
			</tr>
			<tr>
				<th>Updated</th>
				<th><%=@subject.updated_at %></td>
				</tr>
			</table>
		</div>